// Generated by CoffeeScript 1.2.1-pre
(function() {

  google.load('jquery', '1.7.1');

  google.setOnLoadCallback(function() {
    var gmaps, map, style_line_active, style_line_hidden, style_line_inactive;
    gmaps = google.maps;
    map = new gmaps.Map($('#map_canvas').get(0), {
      center: new gmaps.LatLng(56.8333, 60.5833),
      zoom: 12,
      mapTypeId: gmaps.MapTypeId.ROADMAP
    });
    style_line_active = {
      strokeOpacity: 1.0,
      strokeWeight: 3,
      strokeColor: '#f00'
    };
    style_line_inactive = {
      strokeOpacity: 0.5,
      strokeWeight: 2,
      strokeColor: '#00f'
    };
    style_line_hidden = {
      strokeOpacity: 0.1,
      strokeWeight: 2,
      strokeColor: '#00f'
    };
    return $.getJSON("/proxy/urbus_route_threads", function(threads, status, req) {
      var line_over_lock, thread, thread_lines, _i, _len, _results;
      thread_lines = {};
      line_over_lock = false;
      _results = [];
      for (_i = 0, _len = threads.length; _i < _len; _i++) {
        thread = threads[_i];
        _results.push((function(thread) {
          $.getJSON("/proxy/urbus_route_thread_" + thread, function(pos_data, status, req) {
            var line, pos;
            line = thread_lines[thread] = new gmaps.Polyline({
              map: map,
              path: (function() {
                var _j, _len1, _results1;
                _results1 = [];
                for (_j = 0, _len1 = pos_data.length; _j < _len1; _j++) {
                  pos = pos_data[_j];
                  _results1.push(new gmaps.LatLng(pos.latitude, pos.longitude));
                }
                return _results1;
              })(),
              clickable: true
            });
            line.setOptions(style_line_inactive);
            gmaps.event.addListener(line, 'mouseover', function() {
              if (!line_over_lock) return line.setOptions(style_line_active);
            });
            return gmaps.event.addListener(line, 'mouseout', function() {
              if (!line_over_lock) return line.setOptions(style_line_inactive);
            });
          });
          return $.getJSON("/proxy/urbus_route_vehicles_" + thread, function(pos_data, status, req) {
            var ib, ib_marker, marker, pos, _j, _len1, _results1;
            _results1 = [];
            for (_j = 0, _len1 = pos_data.length; _j < _len1; _j++) {
              pos = pos_data[_j];
              marker = new gmaps.Marker({
                map: map,
                position: new gmaps.LatLng(pos.latitude, pos.longitude),
                visible: false,
                draggable: false,
                clickable: false,
                flat: true
              });
              ib_marker = $("<img src=\"arrow.png\"\ntitle=\"Bus " + thread + ", speed: " + pos.velocity + " km/h\" />").css({
                transform: "rotate(" + pos.course + "deg)",
                '-moz-transform': "rotate(" + pos.course + "deg)",
                '-o-transform': "rotate(" + pos.course + "deg)",
                '-webkit-transform': "rotate(" + pos.course + "deg)"
              }).get(0);
              ib = new InfoBox({
                content: ib_marker,
                disableAutoPan: true,
                pixelOffset: new google.maps.Size(0, 0),
                boxClass: 'marker_box',
                pane: 'floatPane',
                enableEventPropagation: true,
                closeBoxURL: ''
              });
              ib.open(map, marker);
              gmaps.event.addDomListener(ib_marker, 'mouseover', function() {
                var line, _;
                for (_ in thread_lines) {
                  line = thread_lines[_];
                  line.setOptions(style_line_hidden);
                }
                gmaps.event.trigger(thread_lines[thread], 'mouseover');
                return line_over_lock = true;
              });
              _results1.push(gmaps.event.addDomListener(ib_marker, 'mouseout', function() {
                var line, _;
                for (_ in thread_lines) {
                  line = thread_lines[_];
                  line.setOptions(style_line_inactive);
                }
                gmaps.event.trigger(thread_lines[thread], 'mouseout');
                return line_over_lock = false;
              }));
            }
            return _results1;
          });
        })(thread));
      }
      return _results;
    });
  });

}).call(this);
